# -*- coding: utf-8 -*-
"""ngrokiu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SzdnHuKKulwqBRUNHGKl4YI_l3mZE2a
"""

from flask import Flask, jsonify
import requests
import numpy as np

service = Flask(__name__)

model_urls = [
    "http://model1.ngrok.io/predict",
    "http://model2.ngrok.io/predict",
    "http://model3.ngrok.io/predict"
]

@service.route('/aggregate-prediction', methods=['GET'])
def aggregate_prediction():
    try:
        model_outputs = []
        for url in model_urls:
            result = requests.get(url)
            prediction_value = result.json().get('prediction')
            model_outputs.append(prediction_value)
        average_prediction = np.average(model_outputs)
        return jsonify({'average_prediction': average_prediction})
    except Exception as error:
        return jsonify({'error_message': 'Error computing average prediction'}), 500

if __name__ == '__main__':
    service.run(debug=True, host='0.0.0.0', port=8080)