# -*- coding: utf-8 -*-
"""urls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SzdnHuKKulwqBRUNHGKl4YI_l3mZE2a
"""

import requests

model_identifiers = ['model_linear']
ngrok_base_url = 'https://71e2-89-30-29-68.ngrok-free.app/predict/'
query_params = {'feature_values': '7700,1,2,4,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0'}
collected_predictions = []

for identifier in model_identifiers:
    try:
        specific_model_url = f"{ngrok_base_url}{identifier}"
        api_response = requests.get(specific_model_url, params=query_params)
        if api_response.status_code == 200:
            received_prediction = api_response.json().get('prediction')
            collected_predictions.append(received_prediction)
            print(f"Received prediction for {identifier}:", received_prediction)
        else:
            print(f"Error encountered for {identifier}:", api_response.text)
    except Exception as error:
        print(f"Request error for {identifier}:", error)

if collected_predictions:
    consensus_prediction = sum(collected_predictions) / len(collected_predictions)
    print(f"Average prediction across models: {consensus_prediction}")
else:
    print("Failed to obtain predictions due to encountered errors.")